### ISSUE TITLE
Change to required validator breaks expected use on check boxes.

### ISSUE THREAD

**Issue by NJM8** [vuelidate/vuelidate#305] opened 2018-05-23 12:54 UTC
Hello, 

The change in the required validator to return true when val is false breaks the expected use for check boxes. I am expecting that if a checkbox is required and not checked then the validator will show that it is invalid or in error, however with the recent change [here](https://github.com/monterail/vuelidate/commit/b15ba50f07b93b455ff4ae5e3dd69a8d1e25c0bd), required now has no effect on the checkbox. Here are two codesandbox examples to demonstrate:

[0.6.1, working](https://codesandbox.io/s/5mrnq3kvlk)
[0.7.1, broken](https://codesandbox.io/s/jj0qo70k5v)

Is this the new expected behavior or should this be reverted? If this is the new desired behavior perhaps an explicit example for check boxes could be added to the docs, as it requires a custom validator for a basic element.

[0.7.1 with custom validator](https://codesandbox.io/s/n108809qqp)

Thank you.

**Comment by Frizi** [comment] 2018-05-24 08:31
This is new expected behaviour. It probably should be documented in a more direct way, but for now you can check #156 for the reasoning behind this change.

You can easily supplement this with your own `checked` validator that explicitly requires `true` value.

Full-featured implementation would look like this:

```javascript
const checked = helpers.withParams({ type: 'checked' }, (value) =>
  !helpers.req(value) || value === true)
```

You can kinda cheat it too by using functional `sameAs`:

```javascript
const checked = sameAs(() => true)
```

I might end up adding that `checked` validator to the library eventually, but I'd rather wait a little for more potential suggestions.

**Comment by NJM8** [comment] 2018-05-24 12:54
I see, that all makes sense. I hadn't considered the true/false check box case. I am in favor of the checked validator that simply returns true/false to match the state of the checkbox. Then maybe a checkedIf and a checkedUnless would make sense to allow flexibility. 

In my use case the check box should be required unless the user is from a certain country, checkedUnless would allow for that.

**Comment by dobromir-hristov** [comment] 2019-03-02 16:32
Closing as the question was answered. We may add this to the recipe's section later.

**Closed by dobromir-hristov** 2019-03-02 16:32 UTC
Labels: docs, help

**Comment by 4ortytwo** [comment] 2019-12-15 21:27
@NJM8 I'm facing the same issue right now. How did you go about checkedUnless? 

@Frizi Would you please help me with this as I wasn't able to find any solution to the issue?

**Comment by NJM8** [comment] 2019-12-16 13:55
@4ortytwo I just used a custom validator as seen here: https://codesandbox.io/s/n108809qqp

**Comment by 4ortytwo** [comment] 2019-12-16 15:27
@NJM8  Can't wrap my head around how I'd make this requiredToBeCheckedUnless. 

If selectedRace is 'human', I'd like the checkbox to be optional, if selectedRace is anything else, I'd like it to be required.

**Comment by NJM8** [comment] 2019-12-16 15:49
@4ortytwo It's been awhile since I used Vuelidate, but I think this will work for you: https://codesandbox.io/s/required-checked-unless-1wer7

In your custom validator just return true for a valid input unless the species is human.

**Comment by 4ortytwo** [comment] 2019-12-16 16:53
@NJM8 , thank you a lot. It's much simpler than I thought.
