### ISSUE TITLE
$params set to null

### ISSUE THREAD

**Issue by helgefredheim** [vuelidate/vuelidate#874] opened 2021-06-07 08:53 UTC
We have a complicated issue with Vue and Vuelidate, basically we've made a Vue component library with Vue and Vuelidate. The library is built with Rollup.

Some components are validated like so:

    import { maxLength } from 'vuelidate/lib/validators'

    ...

    validations() {
        return {
            value: {
                maxLength: maxLength(4)
            }
        }
    }

    ...

This means the number `4` should be available as a param to be used in an error message. This works in the tests in the lib and also in a standalone Vue app that can be run from the lib. `$v.value.$params` is consequently defined as so:

    {
        maxLength: {
            type: "maxLength",
            max: 4
        }
    }

The 4 can then be used in an error message, e.g. *"you cannot enter more than 4 characters"*.

However, when the lib is imported to another app, the `$v.value.$params` is set to null. Thus the error message becomes: *"you cannot enter more than characters"*.

We've found a couple of issues on this (https://github.com/vuelidate/vuelidate/issues/302, https://github.com/vuelidate/vuelidate/issues/460) but none of the suggested solutions seems to work.

Any help is appreciated!

**Comment by cypherix93** [comment] 2021-06-18 23:01
Figured it out! The issue is in the [withParams.js](https://github.com/vuelidate/vuelidate/blob/master/src/withParams.js) file.

See the following lines:
```
  process.env.BUILD === 'web'
    ? require('./withParamsBrowser').withParams
    : require('./params').withParams
```
**Vuelidate is choosing a different `withParams` function based on the `BUILD` env var.**

@helgefredheim ^ This is most likely why it fails for you in the app that consumes your lib, but your tests in the lib all pass correctly.

---
More from [withParamsBrowser.js](https://github.com/vuelidate/vuelidate/blob/master/src/withParamsBrowser.js):
```
export const withParams = root.vuelidate
    ? root.vuelidate.withParams
    : fakeWithParams
```
Vuelidate is looking for the correct `withParams` function in `window.vuelidate`, which I guess it expects to be available if `process.env.BUILD === 'web'`.

If `window.vuelidate` is not there, the `withParams` function falls back to a fake one, which I am guessing **causes $params to be null**.

---

### Solution:
```
import * as Vuelidate from 'vuelidate';

window.vuelidate = Vuelidate;
```
My `$params` all have proper values now.

**Comment by dobromir-hristov** [comment] 2021-07-01 21:13
closing as this does not look like an issue, rather a user error

**Closed by dobromir-hristov** 2021-07-01 21:13 UTC
Labels: 0.x, bug

**Comment by leonid-chernyavskiy** [comment] 2022-01-11 10:38
> closing as this does not look like an issue, rather a user error

This one needs to be on documentation or somewhere else (FAQ?)

Also, bug reappears when loading via async modules with webpack chunking enabled. Runtime selection of "withParams" would somehow make life easier:

src/withParamsBrowser.js, last export, change to:
`export const withParams = function () {
    return (root.vuelidate
        ? root.vuelidate.withParams
        : fakeWithParams).apply(null, arguments);
}`

**Comment by tada5hi** [comment] 2022-02-21 18:56
in my case it doesnt work, whether i set the window.vuelidate in the consuming app.
@helgefredheim how did you solve it ?

As an annotation i only use vuelidate as peer-dependeny in the library.

**Comment by tada5hi** [comment] 2022-02-21 19:23
@dobromir-hristov what is the solution in your eyes ?

**Comment by leonid-chernyavskiy** [comment] 2022-02-22 11:06
This is an ugly monkey-patch, though, it works:

https://gist.github.com/leonid-chernyavskiy/a08395005da5eacf8f2f293ce544f594

**Comment by tada5hi** [comment] 2022-02-22 11:22
Thx for the fast response and the attempt to help :blush: . In my case, the browser mode was not the actually problem. I even manipulated the vuelidate lib in node_modules and removed the `withParamsBrowser.js` file and the condition in `withParams.js`. Than i noticed that, some parts of the `vuelidate` lib were still part of my rollup bundle. 
The problem was, that i had to explicit define `vuelidate/lib/validators` in adddition to the base module path (`vuelidate`) in the rollup config as external.
Now everything is working fine :innocent:

**Comment by ayushbhatt-7** [comment] 2022-03-09 20:05
I'm using vuelidate (0.7.5) with VuelidateErrorExtractor(2.4.1) this way : 

`import Vuelidate from "vuelidate";
import VuelidateErrorExtractor, {
  templates
} from "vuelidate-error-extractor";

const messages = {minLength: "{attribute} must have minimum {min} characters"}

Vue.use(Vuelidate);
Vue.use(VuelidateErrorExtractor, {
  messages,
  attributes: {
    name: "Name"}
}`

**{min} stopped working suddenly but {attribute} is working
$params is set to null in my case as well**

Tried above solution but none worked.
Can you help with some alternative solution ? @tada5hi @dobromir-hristov

**Comment by tada5hi** [comment] 2022-03-10 06:01
The problem lies in general on how vuelidate changed their param handling. Your external library (vuelidate-error-extractor) has now to change its rollup configuration.
The library has to specify `vuelidate` + `vuelidate/lib/validators` as externals in the configuration file:
https://github.com/dobromir-hristov/vuelidate-error-extractor/blob/master/config/entry.js

**Comment by tada5hi** [comment] 2022-03-10 06:04
If you are looking for another library to handle the error messages in group let me know. ^^

**Comment by dobromir-hristov** [comment] 2022-03-10 06:04
Vuelidate 0.x had not had a major change in years, nothing has changed.

**Comment by tada5hi** [comment] 2022-03-10 06:06
@dobromir-hristov  I refer to changes made from 0.7.4 to 0.7.7 regarding param handling. But the problem which occured there only targets external library which are build on top on vuelidate and released via a bundler e.g. webpack, rollup etc.

This was a major change for this target group but non in your general versioning.

**Comment by ayushbhatt-7** [comment] 2022-03-10 06:38
> If you are looking for another library to handle the error messages in group let me know. ^^

Although, I want to stick with VEE but if this problem persist I might have to move to some other plugins, Any alternative solution will be helpful. @tada5hi

**Comment by dobromir-hristov** [comment] 2022-03-13 16:51
> If you are looking for another library to handle the error messages in group let me know. ^^

Well that kinda of hurts :D 

> @dobromir-hristov I refer to changes made from 0.7.4 to 0.7.7 regarding param handling. But the problem which occured there only targets external library which are build on top on vuelidate and released via a bundler e.g. webpack, rollup etc.

I am looking at the changes introduced from 0.7.4 to 0.7.7 and there are no changes to the logic related to params or bundling.

I am OK with adding `vuelidate/lib/validators` as part of the externals of Vuelidate-error-extractor, I just dont know why that is needed.

VEE does not import vuelidate at all, so upon building, it should not need that setting as well.

**Comment by tada5hi** [comment] 2022-03-13 19:41
> >  If you are looking for another library to handle the error messages in group let me know. ^^
>
 > Well that kinda of hurts :D

I am sorry ❤️‍🩹. That was not my intention. I just felt a bit agitated when i tried to fix this for a small library where vuelidate is used. 
And to be fair, it is not a library in that scope like you wrote. ^^

> > @dobromir-hristov I refer to changes made from 0.7.4 to 0.7.7 regarding param handling. But the problem which occured there only targets external library which are build on top on vuelidate and released via a bundler e.g. webpack, rollup etc.
> 
> I am looking at the changes introduced from 0.7.4 to 0.7.7 and there are no changes to the logic related to params or bundling.
> 
> I am OK with adding `vuelidate/lib/validators` as part of the externals of Vuelidate-error-extractor, I just dont know why that is needed.
> 
> VEE does not import vuelidate at all, so upon building, it should not need that setting as well.

I must say i didn't dig so deep in the VEE and did not noticed that vuelidate is not included in the bundle at all. So this
should not the be the problem here.
Sorry for unintentionally letting you investigate in the wrong direction @dobromir-hristov.
