### ISSUE TITLE
Asynchronous Validators on the Next branch

### ISSUE THREAD

**Issue by darki73** [vuelidate/vuelidate#703] opened 2020-09-24 19:31 UTC
Good time of the day.  
I've decided to play around with the `next` branch (or `@vuelidate/core` and `@vuelidate/validators`) and i've faced an issue i cannot wrap my head around.

Right now, on the `stable` branch i am using the following validator to perform async validations:
```ts
export function asynchronousValidator (validator: Function, delay: number = 2000) {
    let currentTimer: NodeJS.Timeout|null = null;
    let currentPromiseReject: any = null;

    const debounce = () : Promise<void> => new Promise((resolve, reject) => {
        currentTimer = setTimeout(() => {
            currentTimer = null;
            currentPromiseReject = null;
            resolve();
        }, delay);
        currentPromiseReject = reject;
    });

    return (value: any) => {
        if (currentTimer) {
            currentPromiseReject(new Error('Replaced'));
            clearTimeout(currentTimer);
            currentTimer = null;
        }
        // @ts-ignore
        return validator.call(this, value, debounce);
    }
}
```
and i have this validation in place:
```ts
username: {
    required,
    minLength: minLength(8),
    maxLength: maxLength(32),
    isUnique: asynchronousValidator(function (value: string, debounce: Function) {
        if (isUndefinedOrNull(value) || value === '') {
            return true;
        }
        return debounce()
            .then(() => PeopleService.usernameExists(value))
            .then((exists: boolean) => !exists)
            .catch(() => false);
    }, 1200)
}
```

However, on the `next` branch, there is a new way of creating `asynchronous validators`.
By going through the source code, i found that you can do the following `common.withAsync((value: string) => {});`

However, for some reason, there is no way in adapting the code i have (for input debouncing). Either it is not working at all, it gets called (by using the `console.log` i can see that each part of it is working), but there is no output (validation not happens). 
Or, it constantly throwing errors about not being able to access the `.then` method as it does not exists.

I've tried this
```ts
export function asynchronousValidator (validator: Function, delay: number = 2000) {
    let currentTimer: NodeJS.Timeout|null = null;
    let currentPromiseReject: any = null;

    const debounce = () : Promise<void> => new Promise((resolve, reject) => {
        currentTimer = setTimeout(() => {
            currentTimer = null;
            currentPromiseReject = null;
            resolve();
        }, delay);
        currentPromiseReject = reject;
    });

    return withAsync((value: any) => {
        if (currentTimer) {
            currentPromiseReject(new Error('Replaced'));
            clearTimeout(currentTimer);
            currentTimer = null;
        }
        // @ts-ignore
        return validator.call(this, value, debounce);
    });
}
```

But as i said, no result is returned, or this error is thrown (yes, can be both, no idea why).
![image](https://user-images.githubusercontent.com/1318627/94190957-a878e700-fe61-11ea-82b6-2de9b7e35d5d.png)

 I am using latest `Vue 2` with latest `composition-api` on latest `nuxtjs`

**Comment by shentao** [comment] 2020-09-24 19:54
Hey!

Could you try creating a codesandbox/jsfiddle with this use case?

**Comment by dobromir-hristov** [comment] 2020-09-24 20:07
To be honest, asynchronous validations are a bit uncharted territory. We will be ironing them out as we go. 

In the meantime as Damian said, please make us a sandbox and we will try to help as soon as we can.

**Comment by darki73** [comment] 2020-09-24 22:35
@shentao @dobromir-hristov 
Here is an example https://codesandbox.io/s/gracious-turing-40g56?file=/pages/index.vue

At line 146 and 147, there is a comment about what you can try to do with the code.
Also, toggle the console view, or you will miss the error.
![image](https://user-images.githubusercontent.com/1318627/94206984-87bd8b00-fe7b-11ea-9959-4bfbcbcb59c7.png)

**Comment by darki73** [comment] 2020-09-28 07:24
So, any idea on what might be wrong with the existing code?

**Comment by darki73** [comment] 2020-09-29 03:33
Also, for some reason, when using the following piece of code it creates duplicate validation calls (1 -> 2 -> 4 -> 8 -> 16 -> 32 -> so on).

So on the first validation call, it will work just fine, however, after that it will validate every single character inputted to the text field, ignoring debounce, and then it will 'debounce' the input and will validate again at the end.

Using `lodash/debounce`:
```ts
const onEmailInput = debounce(() => {
    data.$v.value.administrator.information.email.$touch();
}, 1200, { leading: false, trailing: true });
```

This piece of code works just fine, waits 1.2s for the input to stop and then fires the `fetch`
```ts
const onEmailInput = debounce(() => {
    fetch('https://jsonplaceholder.typicode.com/todos/1');
}, 1200);
```

Here is how the actual input field looks like:
```vue
<v-text-field
    autocomplete="new-email"
    v-model="administrator.information.email"
     :label="$t('console.administrators.people.fields.email.label')"
    :placeholder="$t('console.administrators.people.fields.email.placeholder')"
    @input="onEmailInput"
    :error-messages="emailErrors"
    outlined
/>
```

**Comment by Jaimies** [comment] 2020-11-04 08:39
@shentao @dobromir-hristov I have created an MCVE: https://codesandbox.io/s/vuelidate-async-validator-k0ir8.
When the code runs, the following error shows up:
```
[vuelidate] detected a raw async validator. Please wrap any async validators in the `withAsync` helper.
```
However, the [documentation](https://vuelidate-next.netlify.app/examples.html#asynchronous-validation) states that asynchronous validators are supported out of the box.

**Comment by dobromir-hristov** [comment] 2020-11-04 08:46
It's an ongoing change. Just use withAsync for now.

**Comment by Jaimies** [comment] 2020-11-04 09:01
I see. I have created a fork of the MCVE and used `helpers.withAsync` in it: https://codesandbox.io/s/vuelidate-async-validator-forked-zqv04. However, `$invalid` and `$error` fields stay false even after focusing and bluring the input. Maybe I am not using `withAsync` correctly?

**Comment by dobromir-hristov** [comment] 2020-11-04 09:09
```js
rule: withAsync(funcReturningPromise)
```

**Comment by Jaimies** [comment] 2020-11-04 09:15
It's working, thank you!

**Comment by outerstorm** [comment] 2020-11-12 22:27
Ran into this same issue and looked at your code sandbox (https://codesandbox.io/s/vuelidate-async-validator-forked-uxtgm), but change the promise to resolve true (rather than false) and the field still shows as invalid?

**Comment by Helmoz** [comment] 2020-11-21 23:42
@dobromir-hristov 
Trying to do like u said before, but when iam typing in input, the async validator triggers multiple times.
Here example: https://codesandbox.io/s/rough-https-vn6j4?file=/pages/index.vue
Try to type something in input and check console. Every next validation triggers +1 times(1 -> 2 -> 3 -> 4 etc.)
Any ideas how to fast fix this, so i can fork repo and fix it local?
Thanks

**Comment by travbus** [comment] 2020-11-29 20:02
I'm interested in a fix to stop multiple triggers also. Thanks for the example though at least I got it working! Even if it calls my api on every key stroke ha who cares though its just a registration form ha

**Comment by dobromir-hristov** [comment] 2021-02-17 09:00
We have done lots of changes to Vuelidate, all validators are now async by default. Closing for now.

**Closed by dobromir-hristov** 2021-02-17 09:00 UTC
Labels: 👨‍🔧 need example

**Comment by prashantnirgun** [comment] 2022-08-18 13:20
I had an issue it works for blur event but when form submit event the ```$touch()``` didn't work it needs to wait till the ```$pending = true```. I am using vue3 composition api and vuelidate. Wrote isEmailAvailable and isUserNameAvailable async functions so it causes delay caused by async request meanwhile when uses hit form submit method. ```$touch()``` is not async so it goes to else part. Is there way I can wait till my ```v$.$pending = true```. I am sure there must be some simple way to handle this.It goes to else condition there should be simple way to handle aysnc pending action in vuelidate
 
My code is as follows
 ```
 setup(prop, { emit }) {
 const rules = computed(() => ({
      full_name: {
        required,
      },
      user_name: {
        required,
        UserNameExist: helpers.withMessage(
          (params) => (params.$response ? params.$response.message : ''),
          helpers.withAsync(isUserNameAvailable)
        ),
        $autoDirty: true,
      },
      email: {
        required,
        email,
        EmailExist: helpers.withMessage(
          'Email address already taken',
          helpers.withAsync(isEmailAvailable)
        ),
        $autoDirty: true,
      },
   },
    }))

    const isEmailAvailable = async () => {
      if (v$.value) {
        const result = await userExists('email', state.email)
        return {
          $valid:
            result.data.status === 'success',
          message: 'Email is already exists"',
          $pending: false,
        }
      }
    }

    const isUserNameAvailable = async () => {
      if (v$.value) {
        const result = await userExists('user_name', state.user_name)
        return {
          $valid:
            result.data.status === 'success',
          message: 'User Name is already taken"',
          $pending: false,
        }
      }
    }
    const v$ = useVuelidate(rules, state, { lazy: true })
    
    const onSubmit = async () => {
      v$.value.$touch()
      if (v$.value.$pending || !v$.value.$error) {
      //save data
      } else {
        console.log('validation error', v$.value.$pending, v$.value)
      }
    }```
