### ISSUE TITLE
[Question]: Access other model properties in validation function

### ISSUE THREAD

**Issue by khorsky** [vuelidate/vuelidate#937] opened 2021-09-19 10:34 UTC
**Is your feature request related to a problem? Please describe.**
I store my validation rules in separate file. When I'm trying to base validation function on other model property - I'm unable to do it.

**Describe the solution you'd like**
According to [doc](https://vuelidate-next.netlify.app/custom_validators.html#accessing-component-instance-from-validator) I was expecting that I should get model as a second parameter. AFAIK I get Vue instance. I'm unable to access other model properties as stated in doc. I'd like use vuelidate as stated in linked [doc](https://vuelidate-next.netlify.app/custom_validators.html#accessing-component-instance-from-validator).

**Additional context**
"@vuelidate/core": "^2.0.0-alpha.25",
"@vuelidate/validators": "^2.0.0-alpha.21",
"vue": "^3.2.6",

**Simplified example**
rules.ts

```
const requireIfActive = (value: string, vm: any) => {
  // how to access model property active?
  // vm.active is undefined
  return false
}

export default {
  name: {
    required: requireIfActive
  }
}

```
TheComponent.vue
```
<script setup lang="ts">
  import rules from './rules'

  const record = ref({
    active: false,
    name: null,
  })

  useVuelidate(rules, record, { $lazy: true })
}
```

Is there anything I'm doing wrong?

**Comment by dobromir-hristov** [comment] 2021-09-20 05:48
If you `console.log(vm)`, what does it give you? Here are a few things to note.

1. `vm.record.value.active` may be what you are looking for? Because the second parameter is the `vm` or the state exposed to the template, not the actual state of the form. This is a regression from Vuelidate 0.x, which I have fixed in #818 , but because its a breaking change I have not yet added it. Plus it will require fixing the types, which I may not be able to.

**Comment by khorsky** [comment] 2021-09-20 07:00
You're right, `vm.record.active` is the thing I was looking for. I was looking for `vm.active`, that failed. 

Somehow I get the idea that `vm.other.nested.field.contains(value)` mentioned in documentation means I could access other properties of validated object only.

I was not expecting to be able to access whole "component state", that really didn't come to my mind. It's a bit surprising so I understand it's an enormous BC.

When I log `vm`, I get a proxy of "some vue component" - that's maximum I can get with my knowledge. I tried vm.$data, vm.$refs - all empty objects.

**Comment by khorsky** [comment] 2021-10-01 08:16
According to your explanation I'm trying to setup relatively simple validation. It's working.

While using collection of items (eg. order has order items), I would like to validate items by an item property.

I'm curious how to get the right item in foreach validation - when I get whole state, how can I identify "my current item"?

I guess my question is related to #939. Is there any way how to access "current state", even through forEach helper? If so, I'd made a PR to documentation with an example of usage - I just miss it...

**Comment by dobromir-hristov** [comment] 2021-10-01 08:21
I have a pr that does this I think. Need to try.

We encourage users to use separate components for collection validations, because it's more performant and eaiser to maintain in the long run.

In any case, I will see what I can do

**Comment by khorsky** [comment] 2021-10-01 10:37
It looks like I'm getting something wrong. I'll try to explain what I'm trying to achieve - it's possible that I'm just using vuelidate in a wrong way. To save thousand words, I tried to use a picture (guess I'm no painter ;-))

![image](https://user-images.githubusercontent.com/160295/135604273-a5f05d16-8b69-4d94-af08-0fce8107bb5c.png)

I thought that I would define validation rules for an order with order items in parent component (order edit form). And I'd use two subcomponents: a list of items (component) and item details (component).

I'm trying to mark possible errors inside these child components. My exact problem is "item 3 is invalid, item fulfilled, date required". And I'm still failing.

**Comment by dobromir-hristov** [comment] 2021-10-03 08:40
I am not sure I get what you need here. As for the `forEach` helper, I can pass the current iterated object to a validator, as as second parameter. Is that something that you feel would help you? For example:

```js
const items = [
  { name: '', surname: '' }, // this entire object gets passed to each rule as a second parameter, pushing the Instance to third.
  { name: '', surname: '' },
]

const sameAsSurname = (value, surroundingState, instance) => value === surroundingState.surname
```
 In order to help you more, I would need to see code :/

**Comment by dobromir-hristov** [comment] 2021-10-03 08:47
Something like this - https://github.com/vuelidate/vuelidate/tree/dhristov/provide-collection-item-to-forEach-helper

**Comment by khorsky** [comment] 2021-10-11 13:01
@dobromir-hristov Ok, I've prepared [simplified example](https://codesandbox.io/s/vuelidate-2-vue-3-composition-api-with-vm-access-forked-2nyoe) of what I'm trying to achieve.

I've got a model with collection. The rules: order needs a name, a fulfilled order item requires a date.

I'm not sure if I'm using vuelidate correctly. With your help I'm able to validate model. But how to mark invalid items (in table / form)?

I was trying to use nested components, but I need one validation on two places. I guess I missed some important point how to correctly compose all things together...

Sorry for bothering you and thanks for help. 

P.S.
I'd like to prepare a PR with information about `forEach` helper parameters. Where would it fit better? [forEach helper section](https://vuelidate-next.netlify.app/custom_validators.html#foreach-helper) or to [Advanced usage](https://vuelidate-next.netlify.app/advanced_usage.html#using-the-new-foreach-helper) section?

**Comment by dobromir-hristov** [comment] 2021-10-17 18:36
#955 should allow you to easily check if a field is valid or not. I would still advise you to use components for validating collections.

**Comment by dobromir-hristov** [comment] 2021-11-03 20:40
This is now merged.

**Closed** 2021-11-03 20:40 UTC

**Comment by khorsky** [comment] 2021-11-27 11:45
@dobromir-hristov Sorry for being late to the party. I tryied new release of vuelidate and I guess that merged PR has the same problem as I described.

As far as I'm able to test, I still get Vue component instance as the second parameter in custom validator. I guess two things may happened:
- my description is not good enough
- there's currently no way how to proceed

I'll try to clarify my intention in a simple example. Let's say, I'm trying to validate this model:
```js
const candidate = {
  name: 'John Doe',
  nationality: 'us',
  age: 19,
  interests: [
    {
      name: 'pilot',
    },
  ],
}
```
When using custom validator `validPresidentCandidate`, I'd expect given model (candidate variable content) as second parameter to directly ask for nationality and age.

If I'd use $each validation rules on `candidate.interests` and use a custom validator `validPilotCandidate` there, I'd expect whole candidate model as second parameter again - to check candidate's age and interest in piloting.

Now I get Vue component as second parameter:
- I depend on the variable name - variable name change (eg. candidate -> person) in component **must be** projected to my custom validator
- I'm able to reach everything in component - that enables hacks but seems inaccurate to me

I'd guess that my proposal would simplify work with custom validators.

I hope that I've clarified my point of vue :-)

Again - thanks for your time and patience!

**Comment by khorsky** [comment] 2021-11-27 12:04
@dobromir-hristov OMG - I'm taking back everything what I've just written!

Couple of minutes later and it works like a charm! It looks like I get a problem with npm update or so, because now I get the behavior I was looking for.

Sorry for inconvenience.

Thanks!
