### ISSUE TITLE
Vue 3 async setup and useVuelidate exception

### ISSUE THREAD

**Issue by antti-koski** [vuelidate/vuelidate#733] opened 2020-10-23 06:55 UTC
Hi,

Hi, I am trying to use vuelidate within Vue 3's async setup. 

Unfortunately useVuelidate fails with "Cannot read property 'uid' of null". The reason is that useVuelidate internally uses getCurrentInstance and it returns null when await is used. Actually, I am not sure if this is vuelidate or Vue 3 bug (or am I doing something wrong)?

```Javascript
<script>
import { reactive } from 'vue'
import { useVuelidate } from "@vuelidate/core";
import { required } from "@vuelidate/validators";

export default {
    name: 'User',

    async setup() {

        const response = await fetch('https://jsonplaceholder.typicode.com/posts/1');
        const user = await reactive(response.json());

        const validationRules = {
            name: { required }            
        };

        const userModel = useVuelidate(validationRules, user);

        return {
            userModel
        }

    }
}
</script>
```

**Comment by dobromir-hristov** [comment] 2020-10-23 06:57
Nope, looks correct to me. We will have to investigate.

**Comment by dobromir-hristov** [comment] 2020-10-24 16:13
Correct me if I am wrong but i thing you should do 
```js
  const response = await fetch('https://jsonplaceholder.typicode.com/posts/1');
  const user = reactive(await response.json());
```

**Comment by antti-koski** [comment] 2020-10-24 16:41
You are right. My bad. I was originally using axios but wanted to make the example more compact by using fetch.

Anyway, the exception is still there.

**Comment by dobromir-hristov** [comment] 2020-10-24 16:42
Could you give us a reproduction link? Something on codesandbox for example.

**Comment by antti-koski** [comment] 2020-10-24 18:13
I couldn't find suitable template for Vue 3 in Codepen. 

I made an example to [Codesandbox](https://codesandbox.io/s/peaceful-dream-kkjch) but vue-demi does not behave there ("Cannot read property 'version' of undefined" in https://kkjch.csb.app/node_modules/vue-demi/lib/v2/index.esm.js:42:34).

I made a sample project to https://github.com/antti-koski/vuelidate-async-setup-error

**Comment by aethr** [comment] 2020-11-02 04:07
I had a look at the reproduction link, and it looks like `getCurrentInstance()` doesn't work consistently for the entirety of the async `setup` call. I added the following to your `setup` method:

```js
        const instance1 = getCurrentInstance();
        const response = await fetch('https://jsonplaceholder.typicode.com/users/1');
        const instance2 = getCurrentInstance();
```
Running this in the browser, we get:
```js
instance1;
// {uid: 1, vnode: {...}, ...}
instance2;
// null
```

The `useVuelidate` call depends on `getCurrentInstance` for a number of things, so I'm not sure how this could be fixed within Vuelidate. There doesn't seem to be an issue for this in the Vue repo, but I'd think we might want to raise it there.

In the meantime, you can re-structure your `setup` implementation a bit and defer the async call until after validation has been setup:

```js
    async setup() {
        const user = ref({});
        const validationRules = {
            name: { required }            
        };
        const userModel = useVuelidate(validationRules, user);

        const response = await fetch('https://jsonplaceholder.typicode.com/users/1');
        user.value = reactive(await response.json());

        return {
            userModel
        }
    }
```

**Comment by dobromir-hristov** [comment] 2020-11-19 20:42
@aethr is right, there are certain limitations, sorry for that for now. We will look into this more in the future.

**Closed by dobromir-hristov** 2020-11-19 20:42 UTC
