### ISSUE TITLE
useVuelidate() does not update after changing nested validation rules

### ISSUE THREAD

**Issue by fsefidabi** [vuelidate/vuelidate#883] opened 2021-06-29 09:55 UTC
I use useVuelidate() from vuelidate-next (composition API) to collect all validations from nested components.

_In parent component_:
`const v$ = useVuelidate()`

The problem is that when rule validations in nested components change, the v$ in the parent component does not update. Why isn't it reactive?

**Comment by dobromir-hristov** [comment] 2021-06-29 13:58
Could you create a reproducible example? Thanks!

**Comment by dobromir-hristov** [comment] 2021-07-01 21:02
The rules are probably not getting updated, because that is done only once at the moment we call `useVuelidate`, so we pass the entire validation structure to the parent. I wonder if we can replace that efficiently...

**Comment by fsefidabi** [comment] 2021-07-03 05:35
Actually, I think I'm missing something.
I'm using nuxt.js (v2.15) with @nuxtjs/composition-api in my project.

I've created reproducible examples with both **Vue3 (composition-api)** and **Nuxt2(@nuxtjs/composition-api)** to compare and find my mistake. The _useVuelidate()_ is totally reactive in Vue3 example and gets update with changes in nested components.

Sandbox links: 
[Vue](https://codesandbox.io/s/currying-cloud-klnfm?file=/src/App.vue)
[Nuxt](https://codesandbox.io/s/nuxtjs-composition-api-example-forked-qkedv?file=/pages/index.vue)

Both examples are exactly the same as each other, and the only difference is in the definition of useVuelidate.

Vue: 
`v$.value = useVuelidate(rules, { mutableValue })
`

Nuxt: 
`v$.value = useVuelidate(rules.value, { mutableValue });
`
Using `useVuelidate(rules, { mutableValue })` in Nuxt make the app crash. 
Could you please help me to solve this problem?

**Comment by oerhahon** [comment] 2021-07-21 11:12
I'm having a similar issue. but with nested objects. here is a re-creation of the [error](https://codesandbox.io/s/agitated-wu-sb220?file=/src/main.js).

**Comment by dobromir-hristov** [comment] 2021-07-21 11:21
> I'm having a similar issue. but with nested objects. here is a re-creation of the [error](https://codesandbox.io/s/agitated-wu-sb220?file=/src/main.js).

Your rules must match the structure of the form state.

You are nesting `form` inside, which you shouldn't

**Comment by dobromir-hristov** [comment] 2021-10-10 14:22
Just tried having nested children, and using a computed property for their rules. If the rules change, so does the instance in the parent. I will close this for now until I get a reproduction to try out.

**Closed by dobromir-hristov** 2021-10-10 14:22 UTC
Labels: bug, 2.0
