### ISSUE TITLE
Dependency Error When Installing NPM Packages

### ISSUE THREAD

**Issue by howardmat** [vuelidate/vuelidate#777] opened 2020-12-28 15:08 UTC
Hi, 
Sorry if this is the wrong place for this but I'm trying to get started with Vuelidate and Vue 3 however when I try to install the packages I get a dependency error related to composition-api:

```
$ npm install @vuelidate/core @vuelidate/validators
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.1.0
npm ERR! Found: vue@3.0.4
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.0" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-beta.22
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.1" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
```
I think I might be doing something wrong here but can't find anything related to my problem online. Here is my package.json from my project: 
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@azure/msal-browser": "^2.7.0",
    "axios": "^0.21.0",
    "core-js": "^3.6.5",
    "mitt": "^2.1.0",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^3.0.2",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-rc.5",
    "vuex": "^4.0.0-rc.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "node-sass": "^5.0.0",
    "sass-loader": "^10.1.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

```
I'm not sure what I'm missing here. Any help pointing me in the right direction is appreciated.

**Comment by eybarta** [comment] 2020-12-30 10:54
I'm getting the same error... using vite/vue3
Have you found the reason for this yet?

**Comment by howardmat** [comment] 2020-12-30 13:04
I haven't found a reason but I was trying to add vuelidate to an existing project. I spun up a new project with Vue 3.0.4 and still getting the same error so I don't think I'm missing anything or doing something wrong. 

Unfortunately I'm very new to Vue in general so wouldn't even know where to start looking.

**Comment by rwparris2** [comment] 2020-12-30 17:36
Same problem.

I can reproduce by using the default vue3 preset from the vue cli, and attempting to install vuelidate.

```
~/projects ❯ node -v                                                                                                                                    
v15.4.0
~/projects ❯ vue -V                                                                                                                                     
@vue/cli 4.5.9
~/projects ❯ vue create vuelidate-test -p __default_vue_3__                                                                                             
~/projects ❯ cd vuelidate-test                                                                                                                      
~/projects/vuelidate-test master ❯ npm install @vuelidate/core                                                                                      
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vuelidate-test@0.1.0
npm ERR! Found: vue@3.0.4
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.0" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-beta.22
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.1" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/robertparris/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robertparris/.npm/_logs/2020-12-30T17_17_24_760Z-debug.log
```

**Comment by howardmat** [comment] 2020-12-31 20:26
@rwparris2 Using LTS worked. Thanks!

**Comment by dobromir-hristov** [comment] 2021-01-04 13:26
How many are still having issues? I have not for once had an issue with installing.

**Comment by eybarta** [comment] 2021-01-05 07:03
I'm still getting error when trying to install:
npm install @vuelidate/core @vuelidate/validators
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: memorials-for-all@0.0.0
npm ERR! Found: vue@3.0.5
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.5" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-beta.22
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.1" from @vuelidate/core@2.0.0-alpha.8
npm ERR!   node_modules/@vuelidate/core
npm ERR!     @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

My package.json:
```
"resolutions": {
    "postcss": "7.0.35"
  },
  "dependencies": {
    "v-calendar": "^3.0.0-alpha.3",
    "vue": "^3.0.5",
    "vue-kinesis": "^2.0.4",
    "vue-router": "^4.0.2"
  },
  "devDependencies": {
    "@tailwindcss/postcss7-compat": "^2.0.2",
    "@vue/compiler-sfc": "^3.0.4",
    "autoprefixer": "^9.8.6",
    "postcss": "^7.0.35",
    "stylus": "^0.54.8",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2",
    "vite": "^1.0.0-rc.13"
  }
```

It seems it's looking for a Vue version lower than 3 for some reason?

**Comment by howardmat** [comment] 2021-01-05 12:58
@dobromir-hristov The issue only happens with NPM Current (15.5.1) version. I was able to get everything using the LTS (14.15.4) version of NPM. 

It seems that the LTS version of NPM throws warnings on the dependencies:
```
npm WARN @vuelidate/core@2.0.0-alpha.8 requires a peer of @vue/composition-api@^1.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN @vuelidate/validators@2.0.0-alpha.5 requires a peer of @vue/composition-api@^1.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
```

Current version of NPM doesn't throw the warnings. It just fails due to the error. For the sake of my issue I think this can be closed but I wasn't sure if I should keep it open for the sake of the current NPM version?

**Comment by dobromir-hristov** [comment] 2021-02-04 21:28
Should be fixed now.

**Closed by dobromir-hristov** 2021-02-04 21:28 UTC

**Comment by JLoaiza-ENG** [comment] 2023-04-25 17:22
I tried to downgrade my npm version to 6.14.9 as wparris2 but I had encountered a new error

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:

**Comment by apeman76** [comment] 2023-05-15 23:08
I have the same error when trying to install with LTS

Now using node v18.15.0 (npm v9.5.0) and vue 3
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: project@0.1.0
npm ERR! Found: vue@3.2.47
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.0.0" from @kalimahapps/vue-icons@1.3.2
npm ERR!   node_modules/@kalimahapps/vue-icons
npm ERR!     @kalimahapps/vue-icons@"^1.3.2" from the root project
npm ERR!   peer vue@"^3.0.0" from @kyvg/vue3-notification@2.9.0
npm ERR!   node_modules/@kyvg/vue3-notification
npm ERR!     @kyvg/vue3-notification@"^2.9.0" from the root project
npm ERR!   9 more (@unhead/vue, @vue/babel-preset-app, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@3.3.2
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from @vuelidate/core@2.0.2
npm ERR!     node_modules/@vuelidate/core
npm ERR!       @vuelidate/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
It works with --legacy-peer-deps
