### ISSUE TITLE
Vuelidate not reacting to array property after first validation, minLength does not work

### ISSUE THREAD

**Issue by shasderias** [vuelidate/vuelidate#832] opened 2021-03-28 14:07 UTC
### Describe the bug
When state object has an array property, Vuelidate ceases to react to changes to that property after first validation.

minLength(1) does not work when validating arrays.

### Reproduction URL
https://codesandbox.io/s/stoic-poincare-tkqw2?file=/src/App.vue

### To Reproduce/Expected Behavior
**Case 1a**
**To  Reproduce**
1. Go to Reproduction URL
2. Click on Validate

Expected: both minLength(1) and required rules to fail
Got: only required rule fails

**Case 1b**
**To  Reproduce**
(following from Case 1a)

1. Click Add

Expected: required rule to pass
Got: required rule is still failing

**Case 2**
**To  Reproduce**
1. Go to Reproduction URL
2. Click on Add
3. Click on Validate (both rules pass, as expected)
4. Click on Delete

Expected: both minLength(1) and required rules to fail
Got: both rules are still passing

**Comment by kozmanbalint** [comment] 2021-03-29 10:35
+1

**Comment by dobromir-hristov** [comment] 2021-03-29 10:40
We will investigate it, thank you both.

**Comment by dobromir-hristov** [comment] 2021-03-29 19:48
Found the problem... @shentao we dont watch `deep: true` the value... should we do that? For arrays it wont trigger with we push/pop etc...

**Comment by shentao** [comment] 2021-03-29 20:28
Ah, I think this might be a regression after changing from computed to watch, as I’m pretty sure this worked before and still works in one of the older alphas.
I just changed it to `ary = ref([])` and passed that directly and it still doesn’t work though, so unsure if the problem is `deep: true`. See https://codesandbox.io/s/jolly-brook-n0rro?file=/src/App.vue

**Comment by dobromir-hristov** [comment] 2021-04-04 11:49
Closed in #833

**Closed by dobromir-hristov** 2021-04-04 11:49 UTC
Labels: 2.0, bug

**Comment by kozmanbalint** [comment] 2021-04-05 15:28
Thanks for the fix! What's the planned date of the upcoming alpha?

**Comment by dobromir-hristov** [comment] 2021-04-05 15:36
Will release today

**Comment by kozmanbalint** [comment] 2021-04-07 11:09
> Will release today

Still can't see it among the tags (neither on npm). Hardly can wait for the release. :-)

**Comment by dobromir-hristov** [comment] 2021-04-07 11:24
should be up. sorry bout that

**Comment by kozmanbalint** [comment] 2021-04-07 12:21
> should be up. sorry bout that

There it is, thanks!
